export const DEFAULT_UID_CONFIG = {
    program: { id: 'a7fnkONqb9j', name: 'GMB Antenatal Care' },
    programStage: { id: 'Lf8RL5NtRlf', name: 'GMB ANC Visit' },
    trackedEntityType: { id: 'OEBi9eDrHs1' },
    attributes: {
        fullName: 'VKRJz9mtevP',
        age: 'u9ID33VU3AD',
        village: 'vac6Uy4IuKN',
        phoneNumber: 'jugQaCRlagJ',
        parity: 'I9V6nUbpylb',
        previousComplications: 'biG1a1swPSw',
    },
    dataElements: {
        bpSystolic: 'dM1lvOLZQuE',
        bpDiastolic: 'rRwRKt67DLn',
        haemoglobin: 'qA5mCfH3DyP',
        weight: 'Mp3x4c5rEFd',
        gestationalAge: 'uJISx4u5fMO',
        visitNumber: 'QPAVGr6jPbF',
        malariaTestResult: 'C8UBFeuT0Lf',
        ironSupplementation: 'ysvn7Epd8js',
        folicAcid: 'Y6HMwissoNL',
        nurseNotes: 'zwK2GpZEM0e',
        dangerSigns: 'gk4skAjyou6',
        nextVisitDate: 'qFVlM1fWJ7y',
    },
}