export const DEFAULT_UID_CONFIG = {
    program: { id: 'vKumfHCLF9s', name: 'GMB Antenatal Care' },
    programStage: { id: 'A2R2I4YmOrc', name: 'GMB ANC Visit' },
    trackedEntityType: { id: 'cQXHcMbqD4I' },
    attributes: {
        fullName: 'omROCoDSoyr',
        age: 'QohQwHtmuLl',
        village: 'tkbQ7hqPXyx',
        phoneNumber: 'sLjCRHmzEOj',
        parity: 't4Bypv91mZK',
        previousComplications: 'khEsCNR5BKZ',
    },
    dataElements: {
        bpSystolic: 'ql9iLU3RHN8',
        bpDiastolic: 'LlBSSd6vVxg',
        haemoglobin: 'ZIEN7UIyDwT',
        weight: 'kQydABid8pI',
        gestationalAge: 'fcxTfRU7rEJ',
        visitNumber: 'i550kxWUNkv',
        malariaTestResult: 'bmSrGr0uOyL',
        ironSupplementation: 'h377xUVPzgd',
        folicAcid: 'YbgbIRWReY7',
        nurseNotes: 'CHyafkvv3BW',
        dangerSigns: 'bX8WQcIDDfm',
        nextVisitDate: 'idRYNERSfos',
    },
}