// src/config/dhis2.js
// AUTO-GENERATED by setup-dhis2.ps1

export const PROGRAM       = { id: 'qUj3z3HdRCp',  name: 'GMB Antenatal Care' }
export const PROGRAM_STAGE = { id: 'zmXZIvVO4EL', name: 'GMB ANC Visit' }
export const TRACKED_ENTITY_TYPE = 'cyIbN5EzHJy'

export const ORG_UNITS = {
    theGambia:     'Rzfp9HU6s3a',
    serrekundaGH:  'jiLoVLhSKi0',
    brikamaHC:     'NqnA4EMGCgy',
    royalVictoria: 'ec73wYWpODj',
    edwardFrancis: 'kj4vnVyMefh',
    farafenni:     'BP9uevHjqMb',
    bundungMCH:    'iVzQ2Z4PfYQ',
}

export const ATTRIBUTES = {
    fullName:              'aqdGlxkphLj',
    age:                   'gzMDDPC7Tv3',
    village:               'O9uge4R3lMf',
    phoneNumber:           'nBi1meL9Mg0',
    parity:                'tgRmloBUeIZ',
    previousComplications: 'cWIIYDNHy2K',
}

export const DATA_ELEMENTS = {
    bpSystolic:          'MDmOjwKMyGG',
    bpDiastolic:         'xpGOzUpl5WS',
    haemoglobin:         'ZWLzHdbKSQA',
    weight:              'nBJYiYgrZ4u',
    gestationalAge:      'hZ6cO2XCQ4O',
    visitNumber:         'h0uIk6heVSh',
    malariaTestResult:   'fCCXPKBKudb',
    ironSupplementation: 'ZB87jyrzjm6',
    folicAcid:           'uJhItUpocgl',
    nurseNotes:          'CFwPIDXnmcc',
    dangerSigns:         'uEtHFpv96kP',
    nextVisitDate:       'wecYDUtCSlI',
}

export const THRESHOLDS = {
    AGE_MIN: 18, AGE_MAX: 35,
    BP_SYSTOLIC_HIGH: 140, BP_DIASTOLIC_HIGH: 90,
    BP_SYSTOLIC_SEVERE: 160, BP_DIASTOLIC_SEVERE: 110,
    HB_NORMAL_MIN: 11.0, HB_MODERATE_ANAEMIA: 8.0, HB_SEVERE_ANAEMIA: 7.0,
    ANC_MINIMUM_VISITS: 4, FIRST_TRIMESTER_WEEKS: 13,
    GRAND_MULTIPARA_THRESHOLD: 4, SCORE_HIGH: 40, SCORE_MODERATE: 20,
}

export const MALARIA_RESULTS = [
    'Negative', 'Positive (P. falciparum)', 'Positive (P. vivax)', 'Not done',
]

export const DANGER_SIGN_OPTIONS = [
    'Severe headache', 'Blurred vision', 'Severe abdominal pain',
    'Vaginal bleeding', 'Convulsions', 'Difficulty breathing',
    'Reduced fetal movement', 'Swelling of face/hands',
]

export const COMPLICATION_OPTIONS = [
    'None', 'Pre-eclampsia', 'Gestational diabetes', 'Placenta previa',
    'Previous C-section', 'Postpartum haemorrhage', 'Anaemia',
    'Preterm birth', 'Stillbirth', 'Miscarriage',
]

export const RISK_COLORS = {
    high:     { main: '#dc2626', light: '#fef2f2', border: '#fecaca', dark: '#991b1b' },
    moderate: { main: '#d97706', light: '#fffbeb', border: '#fde68a', dark: '#92400e' },
    normal:   { main: '#16a34a', light: '#f0fdf4', border: '#bbf7d0', dark: '#14532d' },
}