// src/config/dhis2.js
// AUTO-GENERATED by setup-dhis2.ps1

export const PROGRAM       = { id: 'a7fnkONqb9j',  name: 'GMB Antenatal Care' }
export const PROGRAM_STAGE = { id: 'Lf8RL5NtRlf', name: 'GMB ANC Visit' }
export const TRACKED_ENTITY_TYPE = 'OEBi9eDrHs1'

export const ORG_UNITS = {
    theGambia:     'hv767dzIjmf',
    serrekundaGH:  'lazFZ3OXZZo',
    brikamaHC:     'Brgt9SPZdln',
    royalVictoria: 'J8BnZVnCKNu',
    edwardFrancis: 'xWl1s8BLexE',
    farafenni:     'xOVhfQY129F',
    bundungMCH:    'C3u5Hr9DhUJ',
}

export const ATTRIBUTES = {
    fullName:              'VKRJz9mtevP',
    age:                   'u9ID33VU3AD',
    village:               'vac6Uy4IuKN',
    phoneNumber:           'jugQaCRlagJ',
    parity:                'I9V6nUbpylb',
    previousComplications: 'biG1a1swPSw',
}

export const DATA_ELEMENTS = {
    bpSystolic:          'dM1lvOLZQuE',
    bpDiastolic:         'rRwRKt67DLn',
    haemoglobin:         'qA5mCfH3DyP',
    weight:              'Mp3x4c5rEFd',
    gestationalAge:      'uJISx4u5fMO',
    visitNumber:         'QPAVGr6jPbF',
    malariaTestResult:   'C8UBFeuT0Lf',
    ironSupplementation: 'ysvn7Epd8js',
    folicAcid:           'Y6HMwissoNL',
    nurseNotes:          'zwK2GpZEM0e',
    dangerSigns:         'gk4skAjyou6',
    nextVisitDate:       'qFVlM1fWJ7y',
}

export const THRESHOLDS = {
    AGE_MIN: 18, AGE_MAX: 35,
    BP_SYSTOLIC_HIGH: 140, BP_DIASTOLIC_HIGH: 90,
    BP_SYSTOLIC_SEVERE: 160, BP_DIASTOLIC_SEVERE: 110,
    HB_NORMAL_MIN: 11.0, HB_MODERATE_ANAEMIA: 8.0, HB_SEVERE_ANAEMIA: 7.0,
    ANC_MINIMUM_VISITS: 4, FIRST_TRIMESTER_WEEKS: 13,
    GRAND_MULTIPARA_THRESHOLD: 4, SCORE_HIGH: 40, SCORE_MODERATE: 20,
}

export const MALARIA_RESULTS = [
    'Negative', 'Positive (P. falciparum)', 'Positive (P. vivax)', 'Not done',
]

export const DANGER_SIGN_OPTIONS = [
    'Severe headache', 'Blurred vision', 'Severe abdominal pain',
    'Vaginal bleeding', 'Convulsions', 'Difficulty breathing',
    'Reduced fetal movement', 'Swelling of face/hands',
]

export const COMPLICATION_OPTIONS = [
    'None', 'Pre-eclampsia', 'Gestational diabetes', 'Placenta previa',
    'Previous C-section', 'Postpartum haemorrhage', 'Anaemia',
    'Preterm birth', 'Stillbirth', 'Miscarriage',
]

export const RISK_COLORS = {
    high:     { main: '#dc2626', light: '#fef2f2', border: '#fecaca', dark: '#991b1b' },
    moderate: { main: '#d97706', light: '#fffbeb', border: '#fde68a', dark: '#92400e' },
    normal:   { main: '#16a34a', light: '#f0fdf4', border: '#bbf7d0', dark: '#14532d' },
}