// src/config/dhis2.js
// AUTO-GENERATED by setup-dhis2.ps1

export const PROGRAM       = { id: 'vKumfHCLF9s',  name: 'GMB Antenatal Care' }
export const PROGRAM_STAGE = { id: 'A2R2I4YmOrc', name: 'GMB ANC Visit' }
export const TRACKED_ENTITY_TYPE = 'cQXHcMbqD4I'

export const ORG_UNITS = {
    theGambia:     'GfO84TYxNKs',
    serrekundaGH:  'cWQwqBL470Q',
    brikamaHC:     'sx9TdwFCFeO',
    royalVictoria: 'PB3kfNitQXa',
    edwardFrancis: 'ab7a1Uy90Sd',
    farafenni:     'bu4Kl2A5umG',
    bundungMCH:    'q7YMx6zJxqe',
}

export const ATTRIBUTES = {
    fullName:              'omROCoDSoyr',
    age:                   'QohQwHtmuLl',
    village:               'tkbQ7hqPXyx',
    phoneNumber:           'sLjCRHmzEOj',
    parity:                't4Bypv91mZK',
    previousComplications: 'khEsCNR5BKZ',
}

export const DATA_ELEMENTS = {
    bpSystolic:          'ql9iLU3RHN8',
    bpDiastolic:         'LlBSSd6vVxg',
    haemoglobin:         'ZIEN7UIyDwT',
    weight:              'kQydABid8pI',
    gestationalAge:      'fcxTfRU7rEJ',
    visitNumber:         'i550kxWUNkv',
    malariaTestResult:   'bmSrGr0uOyL',
    ironSupplementation: 'h377xUVPzgd',
    folicAcid:           'YbgbIRWReY7',
    nurseNotes:          'CHyafkvv3BW',
    dangerSigns:         'bX8WQcIDDfm',
    nextVisitDate:       'idRYNERSfos',
}

export const THRESHOLDS = {
    AGE_MIN: 18, AGE_MAX: 35,
    BP_SYSTOLIC_HIGH: 140, BP_DIASTOLIC_HIGH: 90,
    BP_SYSTOLIC_SEVERE: 160, BP_DIASTOLIC_SEVERE: 110,
    HB_NORMAL_MIN: 11.0, HB_MODERATE_ANAEMIA: 8.0, HB_SEVERE_ANAEMIA: 7.0,
    ANC_MINIMUM_VISITS: 4, FIRST_TRIMESTER_WEEKS: 13,
    GRAND_MULTIPARA_THRESHOLD: 4, SCORE_HIGH: 40, SCORE_MODERATE: 20,
}

export const MALARIA_RESULTS = [
    'Negative', 'Positive (P. falciparum)', 'Positive (P. vivax)', 'Not done',
]

export const DANGER_SIGN_OPTIONS = [
    'Severe headache', 'Blurred vision', 'Severe abdominal pain',
    'Vaginal bleeding', 'Convulsions', 'Difficulty breathing',
    'Reduced fetal movement', 'Swelling of face/hands',
]

export const COMPLICATION_OPTIONS = [
    'None', 'Pre-eclampsia', 'Gestational diabetes', 'Placenta previa',
    'Previous C-section', 'Postpartum haemorrhage', 'Anaemia',
    'Preterm birth', 'Stillbirth', 'Miscarriage',
]

export const RISK_COLORS = {
    high:     { main: '#dc2626', light: '#fef2f2', border: '#fecaca', dark: '#991b1b' },
    moderate: { main: '#d97706', light: '#fffbeb', border: '#fde68a', dark: '#92400e' },
    normal:   { main: '#16a34a', light: '#f0fdf4', border: '#bbf7d0', dark: '#14532d' },
}